### ISSUE TITLE
Conflict with dplyr package

### ISSUE THREAD

**Issue by kaji331** [dphiggs01/wormcat#3]
The function ".worm_cat_fisher_test" depends on "plyr" package for "rename" function. If users load "dplyr" package with "library(dplyr)" after "library(wormcat)", the ".worm_cat_fisher_test" would use "rename" function from "dplyr" package not "plyr" package. This will commit errors!

**Comment by dphiggs01** [comment]
I have added code to **worm_cat_fisher_test.R** to scope the rename call specifically to plyr.
This should address the outstanding issue. This code change is reflected in the master and release v2.0.1
